import assert from 'node:assert/strict'
import test from 'node:test'
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { createHash } from 'node:crypto'
import { fixture, diskView } from './helpers/workflow-crash-fixture.mjs'

const options = { timeout: 90000 }
const sha = bytes => createHash('sha256').update(bytes).digest('hex')
const file = h => join(h.directory, 'src/native.js')
const checks = async h => (await readFile(join(h.directory, 'recovery-checks.jsonl'), 'utf8')).trim().split('\n').map(JSON.parse)
const role = (receipt, id) => receipt.snapshot.run.agents.find(agent => agent.taskId === id)
function noAutomaticWork(receipt) {
  assert.equal(receipt.requests.length, 0)
  assert.equal(receipt.questions.length, 0)
  assert.equal(receipt.liveAgents.length, 1)
}

test('critical crash: partial physical file write preserves its before-image, remains unknown and never becomes an artifact', options, async t => {
  const h = await fixture(t, 'file-write'), active = await h.host('file-write')
  const partial = await readFile(file(h), 'utf8')
  assert.notEqual(partial, 'export const nativeReady = "original"\n')
  assert.notEqual(partial, 'export const nativeReady = true\n')
  const before = await h.cut(active)
  const checkpoint = Object.values(before.state.checkpoints)[0], entry = checkpoint.files['src/native.js']
  assert.deepEqual(entry.after, entry.before, 'No false after-image was committed')
  const original = await readFile(join(h.directory, 'journal/workspace-checkpoints', entry.before.digest + '.bin'))
  assert.equal(sha(original), entry.before.digest)
  assert.equal(original.toString(), 'export const nativeReady = "original"\n')
  assert.equal(Object.values(before.state.records).filter(record => record.kind === 'artifact').length, 0)
  const cold = await h.host('cold'), after = cold.ready
  noAutomaticWork(after)
  assert.equal(role(after, 'implementation').runtimeIssue.status, 'unknown')
  assert.equal(after.snapshot.run.outcome, null)
  assert.equal(after.snapshot.run.ledger.pass, 0)
  assert.deepEqual(after.state.checkpoints, before.state.checkpoints)
  assert.equal(await readFile(file(h), 'utf8'), partial, 'Cold recovery neither completes nor rolls back a partial write')
  const refused = await cold.request('probe-advance')
  assert.equal(refused.detail.accepted, false)
  assert.deepEqual(refused.snapshot, after.snapshot)
  await h.save('partial-file-preserved-before-image-retained', { ...refused, partialSha256: sha(partial), originalSha256: entry.before.digest })
  await h.repeated(cold, after)
  assert.equal(await readFile(file(h), 'utf8'), partial)
})

test('critical crash: a committed return keeps versions and one-attempt limit; explicit resume fully revalidates before delivery', options, async t => {
  const h = await fixture(t, 'rework'), active = await h.host('rework')
  const before = await h.cut(active), oldEngineer = role(active.ready, 'implementation')
  assert.equal(before.state.returns.length, 1)
  assert.equal(before.state.returns[0].attempt, 1)
  assert.equal(before.snapshot.run.outcome, null)
  assert.equal(before.snapshot.run.ledger.hardOutcome, 'PENDING')
  assert.equal((await checks(h)).length, 1)
  assert.equal((await checks(h))[0].value, false, 'The failed check was a real process result')
  const cold = await h.host('cold'), after = cold.ready
  noAutomaticWork(after)
  assert.deepEqual(after.state.records, before.state.records)
  assert.deepEqual(after.state.returns, before.state.returns)
  assert.equal(after.snapshot.run.ledger.hardOutcome, 'PENDING')
  assert.equal(role(after, 'implementation').runtimeIssue, undefined, 'Idle roles are not classified as running orphans')
  await h.save('returned-work-not-auto-resumed', after)
  await h.repeated(cold, after)
  const resumed = await h.host('cold')
  const implemented = await resumed.request('explicit-advance')
  assert.equal(role(implemented, 'implementation').agentSessionId, oldEngineer.agentSessionId)
  assert.equal(role(implemented, 'implementation').taskVersion, before.state.records['task:implementation'].version)
  assert.equal(role(implemented, 'implementation').status, 'idle')
  assert.equal(implemented.snapshot.run.ledger.hardOutcome, 'PENDING')
  const verified = await resumed.request('explicit-advance')
  assert.equal(role(verified, 'engineering-test').status, 'idle')
  assert.equal(role(verified, 'code-review').status, 'idle')
  assert.equal(verified.snapshot.run.ledger.hardOutcome, 'PENDING', 'Engineering PASS cannot reuse an old black-box verdict')
  const accepted = await resumed.request('explicit-advance')
  assert.equal(role(accepted, 'acceptance').status, 'idle')
  const delivered = await resumed.request('explicit-advance')
  assert.equal(delivered.snapshot.run.outcome, 'PASS')
  assert.equal(delivered.state.returns.length, 1)
  assert.deepEqual((await checks(h)).map(item => item.value), [false, true, true])
  assert.equal(Object.values(delivered.state.commands).length, 3)
  assert.deepEqual(delivered.snapshot.run.budget.used.commands, 3)
  await h.save('explicit-same-child-rework-and-fresh-verification', delivered)
  await h.repeated(resumed, delivered)
})

test('critical crash: verified-but-undelivered work stays undecided until explicit delivery, without rerunning roles', options, async t => {
  const h = await fixture(t, 'delivery'), active = await h.host('delivery')
  const before = await h.cut(active)
  assert.equal(before.snapshot.run.outcome, null)
  assert.equal(before.snapshot.run.ledger.hardOutcome, 'PASS')
  const cold = await h.host('cold'), after = cold.ready
  noAutomaticWork(after)
  assert.equal(after.snapshot.run.outcome, null)
  assert.deepEqual(after.state.records, before.state.records)
  await h.repeated(cold, after)
  const resumed = await h.host('cold')
  const delivered = await resumed.request('explicit-advance')
  assert.equal(delivered.snapshot.run.outcome, 'PASS')
  assert.equal(delivered.requests.length, 0, 'Delivery consumes current evidence, no new model or role')
  assert.equal((await checks(h)).length, 2)
  // Official tool output is { value: { result: JSON string } }, not a raw controller result.
  const artifact = JSON.parse(delivered.detail.result.value.result).deliverables
  assert.equal(artifact.length, 1, 'Public delivery exposes its current file provenance')
  assert.equal(artifact[0].relativePath, 'src/native.js')
  assert.equal(artifact[0].digest, sha(await readFile(file(h))))
  const duplicate = await resumed.request('probe-advance')
  assert.equal(duplicate.detail.accepted, false)
  assert.deepEqual(duplicate.snapshot, delivered.snapshot)
  await h.save('explicit-delivery-only-once', delivered)
  await h.repeated(resumed, delivered)
})

test('critical crash: post-check external file changes prevent stale PASS delivery after a cold reopen', options, async t => {
  const h = await fixture(t, 'delivery-changed', 'delivery'), active = await h.host('delivery')
  const before = await h.cut(active)
  await writeFile(file(h), 'export const nativeReady = "external edit"\n')
  const cold = await h.host('cold'), after = cold.ready
  noAutomaticWork(after)
  const refused = await cold.request('probe-advance')
  assert.equal(refused.detail.accepted, false)
  assert.match(refused.detail.error, /changed after implementation report/)
  assert.equal(refused.snapshot.run.outcome, null)
  assert.deepEqual(refused.state.records, before.state.records)
  assert.equal((await checks(h)).length, 2)
  await h.save('changed-file-delivery-denied', refused)
  await h.repeated(cold, after)
  assert.equal(await readFile(file(h), 'utf8'), 'export const nativeReady = "external edit"\n')
})

test('critical crash: one adopted rule and one pending revision survive; old answer is rejected and only the pending item is re-asked', options, async t => {
  const h = await fixture(t, 'learning'), active = await h.host('learning')
  assert.ok(active.ready.nativeQuestion)
  const before = await h.cut(active)
  assert.deepEqual(before.snapshot.run.learning.candidates.map(item => item.status), ['accepted', 'pending'])
  assert.equal(before.state.learningRevisions.length, 1)
  const acceptedId = before.state.learningDecision.acceptedIds[0]
  const cold = await h.host('cold'), after = cold.ready
  noAutomaticWork(after)
  assert.equal(after.snapshot.run.outcome, 'PASS')
  assert.deepEqual(after.snapshot.run.learning, before.snapshot.run.learning)
  assert.deepEqual(after.activeRules.map(item => item.ruleId), [acceptedId])
  await h.repeated(cold, after)
  const resumed = await h.host('cold')
  const rejected = await resumed.request('finish-learning', { oldQuestionId: active.ready.nativeQuestion.question.id })
  assert.equal(rejected.detail.accepted, false)
  assert.deepEqual(rejected.snapshot, after.snapshot)
  assert.equal(rejected.activeRules.length, 1)
  const finished = await resumed.request('finish-learning')
  assert.equal(finished.detail.accepted, true, JSON.stringify(finished.detail))
  assert.equal(finished.snapshot.run.learning.decisionRecorded, true)
  assert.deepEqual(finished.snapshot.run.learning.candidates.map(item => item.status), ['accepted', 'accepted'])
  assert.equal(finished.state.learningRevisions.length, 1, 'Reopening unchanged revised text is not another revision')
  assert.equal(finished.activeRules.length, 2)
  assert.equal(finished.state.learningDecision.acceptedIds.filter(id => id === acceptedId).length, 1)
  assert.equal(finished.requests.length, 0)
  assert.ok(finished.questions.every(item => item.ids.length === 1), 'Already accepted rule is never re-asked')
  assert.notEqual(finished.questions.at(-1).ids[0], active.ready.nativeQuestion.question.id)
  assert.equal((await checks(h)).length, 2, 'Learning recovery does not rerun implementation or checks')
  await h.save('stale-answer-denied-then-single-item-confirmed', { rejected, finished })
  await h.repeated(resumed, finished)
  const durable = await diskView(h.directory, h.rootId)
  assert.equal(durable.record.events.filter(event => event.data.name === 'learning/decided').length, 2)
})
