/** Stable copy shared by the Host gate and its native composer presentation. */
export const REQUIREMENTS_CONFIRM_LABEL = '确认需求理解并允许只读规划'
export const ROLLBACK_CONFIRM_LABEL = '确认撤销这些文件变化'
export const ROLLBACK_CANCEL_LABEL = '保留当前文件'
export const MANUAL_CLOSE_LABEL = '已核实停止及影响，人工结束本轮'
export const KEEP_UNKNOWN_LABEL = '尚未核实，保持阻塞'
export const MANUAL_CLOSE_QUESTION = '已核实旧执行停止及其影响，结束本轮吗？'
export const MANUAL_CLOSE_HEADER = '人工处置'
export const BUDGET_HEADER = '本轮预算'
export const BUDGET_KEEP_LABEL = '保持暂停'
export const BUDGET_TOPUP_LABEL = '确认增加本轮额度'
export const BUDGET_END_LABEL = '确认结束本轮，不继续执行'
export const BUDGET_TOPUP_QUESTION = '是否增加本轮执行额度？'
export const BUDGET_END_QUESTION = '是否结束本轮工作流？'
